/* tslint:disable */
/* eslint-disable */
/**
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorInvalidRequest
 */
export interface ErrorInvalidRequest {
    /**
     * 
     * @type {number}
     * @memberof ErrorInvalidRequest
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorInvalidRequest
     */
    message?: string;
}

export function ErrorInvalidRequestFromJSON(json: any): ErrorInvalidRequest {
    return ErrorInvalidRequestFromJSONTyped(json, false);
}

export function ErrorInvalidRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorInvalidRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorInvalidRequestToJSON(value?: ErrorInvalidRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
    };
}


