/* tslint:disable */
/* eslint-disable */
/**
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorNotFound
 */
export interface ErrorNotFound {
    /**
     * 
     * @type {number}
     * @memberof ErrorNotFound
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorNotFound
     */
    message?: string;
}

export function ErrorNotFoundFromJSON(json: any): ErrorNotFound {
    return ErrorNotFoundFromJSONTyped(json, false);
}

export function ErrorNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorNotFound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorNotFoundToJSON(value?: ErrorNotFound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
    };
}


