/* tslint:disable */
/* eslint-disable */
/**
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorValidation
 */
export interface ErrorValidation {
    /**
     * 
     * @type {number}
     * @memberof ErrorValidation
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorValidation
     */
    message?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ErrorValidation
     */
    errors?: { [key: string]: Array<string>; };
}

export function ErrorValidationFromJSON(json: any): ErrorValidation {
    return ErrorValidationFromJSONTyped(json, false);
}

export function ErrorValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorValidation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function ErrorValidationToJSON(value?: ErrorValidation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'errors': value.errors,
    };
}


