/* tslint:disable */
/* eslint-disable */
/**
 * Ducksms
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sender
 */
export interface Sender {
    /**
     * Sender name
     * @type {string}
     * @memberof Sender
     */
    name?: string;
    /**
     * Sender description
     * @type {string}
     * @memberof Sender
     */
    description?: string;
    /**
     * Default sender id
     * @type {boolean}
     * @memberof Sender
     */
    _default?: boolean;
    /**
     * Sender id status
     * @type {string}
     * @memberof Sender
     */
    status?: SenderStatusEnum;
}

export function SenderFromJSON(json: any): Sender {
    return SenderFromJSONTyped(json, false);
}

export function SenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sender {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function SenderToJSON(value?: Sender | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'default': value._default,
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum SenderStatusEnum {
    Active = 'active',
    Inactive = 'inactive'
}


